local d = {}

d.EGDC_3D_DARK_SHADOW = 0
d.EGDC_3D_SHADOW = 1
d.EGDC_3D_FACE = 2
d.EGDC_3D_HIGH_LIGHT = 3
d.EGDC_3D_LIGHT = 4
d.EGDC_ACTIVE_BORDER = 5
d.EGDC_ACTIVE_CAPTION = 6
d.EGDC_APP_WORKSPACE = 7
d.EGDC_BUTTON_TEXT = 8
d.EGDC_GRAY_TEXT = 9
d.EGDC_HIGH_LIGHT = 10
d.EGDC_HIGH_LIGHT_TEXT = 11
d.EGDC_INACTIVE_BORDER = 12
d.EGDC_INACTIVE_CAPTION = 13
d.EGDC_TOOLTIP = 14
d.EGDC_TOOLTIP_BACKGROUND = 15
d.EGDC_SCROLLBAR = 16
d.EGDC_WINDOW = 17
d.EGDC_WINDOW_SYMBOL = 18
d.EGDC_ICON = 19
d.EGDC_ICON_HIGH_LIGHT = 20
d.EGDC_GRAY_WINDOW_SYMBOL = 21
d.EGDC_EDITABLE = 22
d.EGDC_GRAY_EDITABLE = 23
d.EGDC_FOCUSED_EDITABLE = 24

return d
