local code = require("gui/skin/code")
local d = {}

d[code.EGDC_3D_DARK_SHADOW] = 0xFF0A1E3C
d[code.EGDC_3D_FACE] = 0xee2D5BB8
d[code.EGDC_3D_SHADOW] = 0xdd1C3A6E
d[code.EGDC_3D_HIGH_LIGHT] = 0xFF4A90E2
d[code.EGDC_3D_LIGHT] = 0xFF6BB9FF
d[code.EGDC_APP_WORKSPACE] = 0xFF0F2B5A  
d[code.EGDC_BUTTON_TEXT] = 0xFFFFFFFF    
d[code.EGDC_GRAY_TEXT] = 0xFFA7C4E8     
d[code.EGDC_HIGH_LIGHT_TEXT] = 0xFFFFFFFF 
d[code.EGDC_HIGH_LIGHT] = 0xFF00BFFF    
d[code.EGDC_ACTIVE_CAPTION] = 0xffFFFFFF  
d[code.EGDC_INACTIVE_BORDER] = 0x801C3A6E 
d[code.EGDC_ACTIVE_BORDER] = d[code.EGDC_INACTIVE_BORDER]
d[code.EGDC_INACTIVE_CAPTION] = 0xFFA7C4E8 
d[code.EGDC_TOOLTIP] = 0xFFF5D742      
d[code.EGDC_TOOLTIP_BACKGROUND] = 0xDD0A1E3C 
d[code.EGDC_SCROLLBAR] = d[code.EGDC_HIGH_LIGHT]
d[code.EGDC_EDITABLE] = 0xFF1C3A6E     
d[code.EGDC_GRAY_EDITABLE] = 0xFF3A4D6C 
d[code.EGDC_FOCUSED_EDITABLE] = d[code.EGDC_3D_HIGH_LIGHT]
d[code.EGDC_ICON] = 0xFFF5D742         
d[code.EGDC_ICON_HIGH_LIGHT] = 0xFFFF6B00 
d[code.EGDC_WINDOW_SYMBOL] = 0xFFF5D742 
d[code.EGDC_GRAY_WINDOW_SYMBOL] = 0xFFA7C4E8 
d[code.EGDC_WINDOW] = 0xFF0F2B5A       

return d
