#include "in.hpp"

//~ #include "./my_lua/lua.cc"
#include "./libgroup.cc"
#include "./duel.cc"
#include "./group.cc"
#include "./libeffect.cc"
#include "./interpreter.cc"
#include "./libcard.cc"
#include "./operations.cc"
#include "./libduel.cc"
#include "./card.cc"
#include "./processor.cc"
#include "./scriptlib.cc"
#include "./playerop.cc"
#include "./libdebug.cc"
#include "./effect.cc"
#include "./field.cc"

